"""Initialize nkmemo entity..

Revision ID: 29244da58bdc
Revises: a47210ac4893
Create Date: 2022-08-28 08:09:47.908239

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29244da58bdc'
down_revision = 'a47210ac4893'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
