"""Auto

Revision ID: 3ee8518a38e0
Revises: 8d181ce2e90d
Create Date: 2022-08-25 14:32:17.650848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ee8518a38e0'
down_revision = '8d181ce2e90d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
