"""Auto

Revision ID: 83a1692198df
Revises: 9b4de2c168f9
Create Date: 2022-08-25 18:19:57.547658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83a1692198df'
down_revision = '9b4de2c168f9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
