"""Auto

Revision ID: 8d181ce2e90d
Revises: bbb166693dbd
Create Date: 2022-08-25 14:31:58.238131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d181ce2e90d'
down_revision = 'bbb166693dbd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
