"""Auto

Revision ID: 9b4de2c168f9
Revises: f918fb82fb46
Create Date: 2022-08-25 18:19:34.859290

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9b4de2c168f9'
down_revision = 'f918fb82fb46'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('board_tbl', 'lv',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('board_tbl', 'lv',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
