"""Auto

Revision ID: a91b7fd7acea
Revises: 66d37cf976f4
Create Date: 2022-08-25 14:21:15.771197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a91b7fd7acea'
down_revision = '66d37cf976f4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
