"""Auto

Revision ID: bbb166693dbd
Revises: e1729f990e7d
Create Date: 2022-08-25 14:31:33.223850

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bbb166693dbd'
down_revision = 'e1729f990e7d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('board_tbl', 'lv',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('board_tbl', 'lv',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
