"""Initialize nkmemo entity..

Revision ID: bece5a0e6c91
Revises: 29244da58bdc
Create Date: 2022-08-28 08:10:16.971267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bece5a0e6c91'
down_revision = '29244da58bdc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
