"""Auto

Revision ID: ddf1118a07bd
Revises: a91b7fd7acea
Create Date: 2022-08-25 14:22:26.757821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddf1118a07bd'
down_revision = 'a91b7fd7acea'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_tbl_password', table_name='user_tbl')
    op.create_index(op.f('ix_user_tbl_password'), 'user_tbl', ['password'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_tbl_password'), table_name='user_tbl')
    op.create_index('ix_user_tbl_password', 'user_tbl', ['password'], unique=False)
    # ### end Alembic commands ###
