"""Auto

Revision ID: e1729f990e7d
Revises: c3e23b08716e
Create Date: 2022-08-25 14:31:04.479016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1729f990e7d'
down_revision = 'c3e23b08716e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('board_tbl', sa.Column('lv', sa.Integer(), nullable=False))
    op.drop_index('ix_board_tbl_subject', table_name='board_tbl')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_board_tbl_subject', 'board_tbl', ['subject'], unique=False)
    op.drop_column('board_tbl', 'lv')
    # ### end Alembic commands ###
